Collections:
- Metadata:
    Training Data:
    - Cityscapes
    - ADE20K
    - Pascal VOC 2012 + Aug
    - Pascal Context
    - Pascal Context 59
  Name: deeplabv3
Models:
- Config: configs/deeplabv3/deeplabv3_r50-d8_512x1024_40k_cityscapes.py
  In Collection: deeplabv3
  Metadata:
    backbone: R-50-D8
    crop size: (512,1024)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,1024)
      value: 389.11
    lr schd: 40000
    memory (GB): 6.1
  Name: deeplabv3_r50-d8_512x1024_40k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 79.09
      mIoU(ms+flip): 80.45
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r50-d8_512x1024_40k_cityscapes/deeplabv3_r50-d8_512x1024_40k_cityscapes_20200605_022449-acadc2f8.pth
- Config: configs/deeplabv3/deeplabv3_r101-d8_512x1024_40k_cityscapes.py
  In Collection: deeplabv3
  Metadata:
    backbone: R-101-D8
    crop size: (512,1024)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,1024)
      value: 520.83
    lr schd: 40000
    memory (GB): 9.6
  Name: deeplabv3_r101-d8_512x1024_40k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 77.12
      mIoU(ms+flip): 79.61
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r101-d8_512x1024_40k_cityscapes/deeplabv3_r101-d8_512x1024_40k_cityscapes_20200605_012241-7fd3f799.pth
- Config: configs/deeplabv3/deeplabv3_r50-d8_769x769_40k_cityscapes.py
  In Collection: deeplabv3
  Metadata:
    backbone: R-50-D8
    crop size: (769,769)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (769,769)
      value: 900.9
    lr schd: 40000
    memory (GB): 6.9
  Name: deeplabv3_r50-d8_769x769_40k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 78.58
      mIoU(ms+flip): 79.89
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r50-d8_769x769_40k_cityscapes/deeplabv3_r50-d8_769x769_40k_cityscapes_20200606_113723-7eda553c.pth
- Config: configs/deeplabv3/deeplabv3_r101-d8_769x769_40k_cityscapes.py
  In Collection: deeplabv3
  Metadata:
    backbone: R-101-D8
    crop size: (769,769)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (769,769)
      value: 1204.82
    lr schd: 40000
    memory (GB): 10.9
  Name: deeplabv3_r101-d8_769x769_40k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 79.27
      mIoU(ms+flip): 80.11
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r101-d8_769x769_40k_cityscapes/deeplabv3_r101-d8_769x769_40k_cityscapes_20200606_113809-c64f889f.pth
- Config: configs/deeplabv3/deeplabv3_r18-d8_512x1024_80k_cityscapes.py
  In Collection: deeplabv3
  Metadata:
    backbone: R-18-D8
    crop size: (512,1024)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,1024)
      value: 72.57
    lr schd: 80000
    memory (GB): 1.7
  Name: deeplabv3_r18-d8_512x1024_80k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 76.7
      mIoU(ms+flip): 78.27
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r18-d8_512x1024_80k_cityscapes/deeplabv3_r18-d8_512x1024_80k_cityscapes_20201225_021506-23dffbe2.pth
- Config: configs/deeplabv3/deeplabv3_r50-d8_512x1024_80k_cityscapes.py
  In Collection: deeplabv3
  Metadata:
    backbone: R-50-D8
    crop size: (512,1024)
    lr schd: 80000
  Name: deeplabv3_r50-d8_512x1024_80k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 79.32
      mIoU(ms+flip): 80.57
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r50-d8_512x1024_80k_cityscapes/deeplabv3_r50-d8_512x1024_80k_cityscapes_20200606_113404-b92cfdd4.pth
- Config: configs/deeplabv3/deeplabv3_r101-d8_512x1024_80k_cityscapes.py
  In Collection: deeplabv3
  Metadata:
    backbone: R-101-D8
    crop size: (512,1024)
    lr schd: 80000
  Name: deeplabv3_r101-d8_512x1024_80k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 80.2
      mIoU(ms+flip): 81.21
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r101-d8_512x1024_80k_cityscapes/deeplabv3_r101-d8_512x1024_80k_cityscapes_20200606_113503-9e428899.pth
- Config: configs/deeplabv3/deeplabv3_r18-d8_769x769_80k_cityscapes.py
  In Collection: deeplabv3
  Metadata:
    backbone: R-18-D8
    crop size: (769,769)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (769,769)
      value: 180.18
    lr schd: 80000
    memory (GB): 1.9
  Name: deeplabv3_r18-d8_769x769_80k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 76.6
      mIoU(ms+flip): 78.26
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r18-d8_769x769_80k_cityscapes/deeplabv3_r18-d8_769x769_80k_cityscapes_20201225_021506-6452126a.pth
- Config: configs/deeplabv3/deeplabv3_r50-d8_769x769_80k_cityscapes.py
  In Collection: deeplabv3
  Metadata:
    backbone: R-50-D8
    crop size: (769,769)
    lr schd: 80000
  Name: deeplabv3_r50-d8_769x769_80k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 79.89
      mIoU(ms+flip): 81.06
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r50-d8_769x769_80k_cityscapes/deeplabv3_r50-d8_769x769_80k_cityscapes_20200606_221338-788d6228.pth
- Config: configs/deeplabv3/deeplabv3_r101-d8_769x769_80k_cityscapes.py
  In Collection: deeplabv3
  Metadata:
    backbone: R-101-D8
    crop size: (769,769)
    lr schd: 80000
  Name: deeplabv3_r101-d8_769x769_80k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 79.67
      mIoU(ms+flip): 80.81
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r101-d8_769x769_80k_cityscapes/deeplabv3_r101-d8_769x769_80k_cityscapes_20200607_013353-60e95418.pth
- Config: configs/deeplabv3/deeplabv3_r101-d16-mg124_512x1024_80k_cityscapes.py
  In Collection: deeplabv3
  Metadata:
    backbone: R-101-D16-MG124
    crop size: (512,1024)
    lr schd: 80000
  Name: deeplabv3_r101-d16-mg124_512x1024_80k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 78.36
      mIoU(ms+flip): 79.84
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r101-d16-mg124_512x1024_80k_cityscapes/deeplabv3_r101-d16-mg124_512x1024_80k_cityscapes_20200908_005644-57bb8425.pth
- Config: configs/deeplabv3/deeplabv3_r18b-d8_512x1024_80k_cityscapes.py
  In Collection: deeplabv3
  Metadata:
    backbone: R-18b-D8
    crop size: (512,1024)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,1024)
      value: 71.79
    lr schd: 80000
    memory (GB): 1.6
  Name: deeplabv3_r18b-d8_512x1024_80k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 76.26
      mIoU(ms+flip): 77.88
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r18b-d8_512x1024_80k_cityscapes/deeplabv3_r18b-d8_512x1024_80k_cityscapes_20201225_094144-46040cef.pth
- Config: configs/deeplabv3/deeplabv3_r50b-d8_512x1024_80k_cityscapes.py
  In Collection: deeplabv3
  Metadata:
    backbone: R-50b-D8
    crop size: (512,1024)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,1024)
      value: 364.96
    lr schd: 80000
    memory (GB): 6.0
  Name: deeplabv3_r50b-d8_512x1024_80k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 79.63
      mIoU(ms+flip): 80.98
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r50b-d8_512x1024_80k_cityscapes/deeplabv3_r50b-d8_512x1024_80k_cityscapes_20201225_155148-ec368954.pth
- Config: configs/deeplabv3/deeplabv3_r101b-d8_512x1024_80k_cityscapes.py
  In Collection: deeplabv3
  Metadata:
    backbone: R-101b-D8
    crop size: (512,1024)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,1024)
      value: 552.49
    lr schd: 80000
    memory (GB): 9.5
  Name: deeplabv3_r101b-d8_512x1024_80k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 80.01
      mIoU(ms+flip): 81.21
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r101b-d8_512x1024_80k_cityscapes/deeplabv3_r101b-d8_512x1024_80k_cityscapes_20201226_171821-8fd49503.pth
- Config: configs/deeplabv3/deeplabv3_r18b-d8_769x769_80k_cityscapes.py
  In Collection: deeplabv3
  Metadata:
    backbone: R-18b-D8
    crop size: (769,769)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (769,769)
      value: 172.71
    lr schd: 80000
    memory (GB): 1.8
  Name: deeplabv3_r18b-d8_769x769_80k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 76.63
      mIoU(ms+flip): 77.51
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r18b-d8_769x769_80k_cityscapes/deeplabv3_r18b-d8_769x769_80k_cityscapes_20201225_094144-fdc985d9.pth
- Config: configs/deeplabv3/deeplabv3_r50b-d8_769x769_80k_cityscapes.py
  In Collection: deeplabv3
  Metadata:
    backbone: R-50b-D8
    crop size: (769,769)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (769,769)
      value: 862.07
    lr schd: 80000
    memory (GB): 6.8
  Name: deeplabv3_r50b-d8_769x769_80k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 78.8
      mIoU(ms+flip): 80.27
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r50b-d8_769x769_80k_cityscapes/deeplabv3_r50b-d8_769x769_80k_cityscapes_20201225_155404-87fb0cf4.pth
- Config: configs/deeplabv3/deeplabv3_r101b-d8_769x769_80k_cityscapes.py
  In Collection: deeplabv3
  Metadata:
    backbone: R-101b-D8
    crop size: (769,769)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (769,769)
      value: 1219.51
    lr schd: 80000
    memory (GB): 10.7
  Name: deeplabv3_r101b-d8_769x769_80k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 79.41
      mIoU(ms+flip): 80.73
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r101b-d8_769x769_80k_cityscapes/deeplabv3_r101b-d8_769x769_80k_cityscapes_20201226_190843-9142ee57.pth
- Config: configs/deeplabv3/deeplabv3_r50-d8_512x512_80k_ade20k.py
  In Collection: deeplabv3
  Metadata:
    backbone: R-50-D8
    crop size: (512,512)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,512)
      value: 67.75
    lr schd: 80000
    memory (GB): 8.9
  Name: deeplabv3_r50-d8_512x512_80k_ade20k
  Results:
    Dataset: ADE20K
    Metrics:
      mIoU: 42.42
      mIoU(ms+flip): 43.28
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r50-d8_512x512_80k_ade20k/deeplabv3_r50-d8_512x512_80k_ade20k_20200614_185028-0bb3f844.pth
- Config: configs/deeplabv3/deeplabv3_r101-d8_512x512_80k_ade20k.py
  In Collection: deeplabv3
  Metadata:
    backbone: R-101-D8
    crop size: (512,512)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,512)
      value: 98.62
    lr schd: 80000
    memory (GB): 12.4
  Name: deeplabv3_r101-d8_512x512_80k_ade20k
  Results:
    Dataset: ADE20K
    Metrics:
      mIoU: 44.08
      mIoU(ms+flip): 45.19
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r101-d8_512x512_80k_ade20k/deeplabv3_r101-d8_512x512_80k_ade20k_20200615_021256-d89c7fa4.pth
- Config: configs/deeplabv3/deeplabv3_r50-d8_512x512_160k_ade20k.py
  In Collection: deeplabv3
  Metadata:
    backbone: R-50-D8
    crop size: (512,512)
    lr schd: 160000
  Name: deeplabv3_r50-d8_512x512_160k_ade20k
  Results:
    Dataset: ADE20K
    Metrics:
      mIoU: 42.66
      mIoU(ms+flip): 44.09
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r50-d8_512x512_160k_ade20k/deeplabv3_r50-d8_512x512_160k_ade20k_20200615_123227-5d0ee427.pth
- Config: configs/deeplabv3/deeplabv3_r101-d8_512x512_160k_ade20k.py
  In Collection: deeplabv3
  Metadata:
    backbone: R-101-D8
    crop size: (512,512)
    lr schd: 160000
  Name: deeplabv3_r101-d8_512x512_160k_ade20k
  Results:
    Dataset: ADE20K
    Metrics:
      mIoU: 45.0
      mIoU(ms+flip): 46.66
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r101-d8_512x512_160k_ade20k/deeplabv3_r101-d8_512x512_160k_ade20k_20200615_105816-b1f72b3b.pth
- Config: configs/deeplabv3/deeplabv3_r50-d8_512x512_20k_voc12aug.py
  In Collection: deeplabv3
  Metadata:
    backbone: R-50-D8
    crop size: (512,512)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,512)
      value: 72.05
    lr schd: 20000
    memory (GB): 6.1
  Name: deeplabv3_r50-d8_512x512_20k_voc12aug
  Results:
    Dataset: Pascal VOC 2012 + Aug
    Metrics:
      mIoU: 76.17
      mIoU(ms+flip): 77.42
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r50-d8_512x512_20k_voc12aug/deeplabv3_r50-d8_512x512_20k_voc12aug_20200617_010906-596905ef.pth
- Config: configs/deeplabv3/deeplabv3_r101-d8_512x512_20k_voc12aug.py
  In Collection: deeplabv3
  Metadata:
    backbone: R-101-D8
    crop size: (512,512)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,512)
      value: 101.94
    lr schd: 20000
    memory (GB): 9.6
  Name: deeplabv3_r101-d8_512x512_20k_voc12aug
  Results:
    Dataset: Pascal VOC 2012 + Aug
    Metrics:
      mIoU: 78.7
      mIoU(ms+flip): 79.95
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r101-d8_512x512_20k_voc12aug/deeplabv3_r101-d8_512x512_20k_voc12aug_20200617_010932-8d13832f.pth
- Config: configs/deeplabv3/deeplabv3_r50-d8_512x512_40k_voc12aug.py
  In Collection: deeplabv3
  Metadata:
    backbone: R-50-D8
    crop size: (512,512)
    lr schd: 40000
  Name: deeplabv3_r50-d8_512x512_40k_voc12aug
  Results:
    Dataset: Pascal VOC 2012 + Aug
    Metrics:
      mIoU: 77.68
      mIoU(ms+flip): 78.78
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r50-d8_512x512_40k_voc12aug/deeplabv3_r50-d8_512x512_40k_voc12aug_20200613_161546-2ae96e7e.pth
- Config: configs/deeplabv3/deeplabv3_r101-d8_512x512_40k_voc12aug.py
  In Collection: deeplabv3
  Metadata:
    backbone: R-101-D8
    crop size: (512,512)
    lr schd: 40000
  Name: deeplabv3_r101-d8_512x512_40k_voc12aug
  Results:
    Dataset: Pascal VOC 2012 + Aug
    Metrics:
      mIoU: 77.92
      mIoU(ms+flip): 79.18
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r101-d8_512x512_40k_voc12aug/deeplabv3_r101-d8_512x512_40k_voc12aug_20200613_161432-0017d784.pth
- Config: configs/deeplabv3/deeplabv3_r101-d8_480x480_40k_pascal_context.py
  In Collection: deeplabv3
  Metadata:
    backbone: R-101-D8
    crop size: (480,480)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (480,480)
      value: 141.04
    lr schd: 40000
    memory (GB): 9.2
  Name: deeplabv3_r101-d8_480x480_40k_pascal_context
  Results:
    Dataset: Pascal Context
    Metrics:
      mIoU: 46.55
      mIoU(ms+flip): 47.81
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r101-d8_480x480_40k_pascal_context/deeplabv3_r101-d8_480x480_40k_pascal_context_20200911_204118-1aa27336.pth
- Config: configs/deeplabv3/deeplabv3_r101-d8_480x480_80k_pascal_context.py
  In Collection: deeplabv3
  Metadata:
    backbone: R-101-D8
    crop size: (480,480)
    lr schd: 80000
  Name: deeplabv3_r101-d8_480x480_80k_pascal_context
  Results:
    Dataset: Pascal Context
    Metrics:
      mIoU: 46.42
      mIoU(ms+flip): 47.53
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r101-d8_480x480_80k_pascal_context/deeplabv3_r101-d8_480x480_80k_pascal_context_20200911_170155-2a21fff3.pth
- Config: configs/deeplabv3/deeplabv3_r101-d8_480x480_40k_pascal_context_59.py
  In Collection: deeplabv3
  Metadata:
    backbone: R-101-D8
    crop size: (480,480)
    lr schd: 40000
  Name: deeplabv3_r101-d8_480x480_40k_pascal_context_59
  Results:
    Dataset: Pascal Context 59
    Metrics:
      mIoU: 52.61
      mIoU(ms+flip): 54.28
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r101-d8_480x480_40k_pascal_context_59/deeplabv3_r101-d8_480x480_40k_pascal_context_59_20210416_110332-cb08ea46.pth
- Config: configs/deeplabv3/deeplabv3_r101-d8_480x480_80k_pascal_context_59.py
  In Collection: deeplabv3
  Metadata:
    backbone: R-101-D8
    crop size: (480,480)
    lr schd: 80000
  Name: deeplabv3_r101-d8_480x480_80k_pascal_context_59
  Results:
    Dataset: Pascal Context 59
    Metrics:
      mIoU: 52.46
      mIoU(ms+flip): 54.09
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/deeplabv3/deeplabv3_r101-d8_480x480_80k_pascal_context_59/deeplabv3_r101-d8_480x480_80k_pascal_context_59_20210416_113002-26303993.pth
