Collections:
- Metadata:
    Training Data:
    - Cityscapes
  Name: cgnet
Models:
- Config: configs/cgnet/cgnet_680x680_60k_cityscapes.py
  In Collection: cgnet
  Metadata:
    backbone: M3N21
    crop size: (680,680)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (680,680)
      value: 32.78
    lr schd: 60000
    memory (GB): 7.5
  Name: cgnet_680x680_60k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 65.63
      mIoU(ms+flip): 68.04
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/cgnet/cgnet_680x680_60k_cityscapes/cgnet_680x680_60k_cityscapes_20201101_110253-4c0b2f2d.pth
- Config: configs/cgnet/cgnet_512x1024_60k_cityscapes.py
  In Collection: cgnet
  Metadata:
    backbone: M3N21
    crop size: (512,1024)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,1024)
      value: 32.11
    lr schd: 60000
    memory (GB): 8.3
  Name: cgnet_512x1024_60k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 68.27
      mIoU(ms+flip): 70.33
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/cgnet/cgnet_512x1024_60k_cityscapes/cgnet_512x1024_60k_cityscapes_20201101_110254-124ea03b.pth
