Collections:
- Metadata:
    Training Data:
    - Cityscapes
    - ADE20K
    - Pascal VOC 2012 + Aug
  Name: psanet
Models:
- Config: configs/psanet/psanet_r50-d8_512x1024_40k_cityscapes.py
  In Collection: psanet
  Metadata:
    backbone: R-50-D8
    crop size: (512,1024)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,1024)
      value: 315.46
    lr schd: 40000
    memory (GB): 7.0
  Name: psanet_r50-d8_512x1024_40k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 77.63
      mIoU(ms+flip): 79.04
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/psanet/psanet_r50-d8_512x1024_40k_cityscapes/psanet_r50-d8_512x1024_40k_cityscapes_20200606_103117-99fac37c.pth
- Config: configs/psanet/psanet_r101-d8_512x1024_40k_cityscapes.py
  In Collection: psanet
  Metadata:
    backbone: R-101-D8
    crop size: (512,1024)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,1024)
      value: 454.55
    lr schd: 40000
    memory (GB): 10.5
  Name: psanet_r101-d8_512x1024_40k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 79.14
      mIoU(ms+flip): 80.19
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/psanet/psanet_r101-d8_512x1024_40k_cityscapes/psanet_r101-d8_512x1024_40k_cityscapes_20200606_001418-27b9cfa7.pth
- Config: configs/psanet/psanet_r50-d8_769x769_40k_cityscapes.py
  In Collection: psanet
  Metadata:
    backbone: R-50-D8
    crop size: (769,769)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (769,769)
      value: 714.29
    lr schd: 40000
    memory (GB): 7.9
  Name: psanet_r50-d8_769x769_40k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 77.99
      mIoU(ms+flip): 79.64
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/psanet/psanet_r50-d8_769x769_40k_cityscapes/psanet_r50-d8_769x769_40k_cityscapes_20200530_033717-d5365506.pth
- Config: configs/psanet/psanet_r101-d8_769x769_40k_cityscapes.py
  In Collection: psanet
  Metadata:
    backbone: R-101-D8
    crop size: (769,769)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (769,769)
      value: 1020.41
    lr schd: 40000
    memory (GB): 11.9
  Name: psanet_r101-d8_769x769_40k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 78.43
      mIoU(ms+flip): 80.26
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/psanet/psanet_r101-d8_769x769_40k_cityscapes/psanet_r101-d8_769x769_40k_cityscapes_20200530_035107-997da1e6.pth
- Config: configs/psanet/psanet_r50-d8_512x1024_80k_cityscapes.py
  In Collection: psanet
  Metadata:
    backbone: R-50-D8
    crop size: (512,1024)
    lr schd: 80000
  Name: psanet_r50-d8_512x1024_80k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 77.24
      mIoU(ms+flip): 78.69
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/psanet/psanet_r50-d8_512x1024_80k_cityscapes/psanet_r50-d8_512x1024_80k_cityscapes_20200606_161842-ab60a24f.pth
- Config: configs/psanet/psanet_r101-d8_512x1024_80k_cityscapes.py
  In Collection: psanet
  Metadata:
    backbone: R-101-D8
    crop size: (512,1024)
    lr schd: 80000
  Name: psanet_r101-d8_512x1024_80k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 79.31
      mIoU(ms+flip): 80.53
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/psanet/psanet_r101-d8_512x1024_80k_cityscapes/psanet_r101-d8_512x1024_80k_cityscapes_20200606_161823-0f73a169.pth
- Config: configs/psanet/psanet_r50-d8_769x769_80k_cityscapes.py
  In Collection: psanet
  Metadata:
    backbone: R-50-D8
    crop size: (769,769)
    lr schd: 80000
  Name: psanet_r50-d8_769x769_80k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 79.31
      mIoU(ms+flip): 80.91
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/psanet/psanet_r50-d8_769x769_80k_cityscapes/psanet_r50-d8_769x769_80k_cityscapes_20200606_225134-fe42f49e.pth
- Config: configs/psanet/psanet_r101-d8_769x769_80k_cityscapes.py
  In Collection: psanet
  Metadata:
    backbone: R-101-D8
    crop size: (769,769)
    lr schd: 80000
  Name: psanet_r101-d8_769x769_80k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 79.69
      mIoU(ms+flip): 80.89
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/psanet/psanet_r101-d8_769x769_80k_cityscapes/psanet_r101-d8_769x769_80k_cityscapes_20200606_214550-7665827b.pth
- Config: configs/psanet/psanet_r50-d8_512x512_80k_ade20k.py
  In Collection: psanet
  Metadata:
    backbone: R-50-D8
    crop size: (512,512)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,512)
      value: 52.88
    lr schd: 80000
    memory (GB): 9.0
  Name: psanet_r50-d8_512x512_80k_ade20k
  Results:
    Dataset: ADE20K
    Metrics:
      mIoU: 41.14
      mIoU(ms+flip): 41.91
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/psanet/psanet_r50-d8_512x512_80k_ade20k/psanet_r50-d8_512x512_80k_ade20k_20200614_144141-835e4b97.pth
- Config: configs/psanet/psanet_r101-d8_512x512_80k_ade20k.py
  In Collection: psanet
  Metadata:
    backbone: R-101-D8
    crop size: (512,512)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,512)
      value: 76.16
    lr schd: 80000
    memory (GB): 12.5
  Name: psanet_r101-d8_512x512_80k_ade20k
  Results:
    Dataset: ADE20K
    Metrics:
      mIoU: 43.8
      mIoU(ms+flip): 44.75
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/psanet/psanet_r101-d8_512x512_80k_ade20k/psanet_r101-d8_512x512_80k_ade20k_20200614_185117-1fab60d4.pth
- Config: configs/psanet/psanet_r50-d8_512x512_160k_ade20k.py
  In Collection: psanet
  Metadata:
    backbone: R-50-D8
    crop size: (512,512)
    lr schd: 160000
  Name: psanet_r50-d8_512x512_160k_ade20k
  Results:
    Dataset: ADE20K
    Metrics:
      mIoU: 41.67
      mIoU(ms+flip): 42.95
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/psanet/psanet_r50-d8_512x512_160k_ade20k/psanet_r50-d8_512x512_160k_ade20k_20200615_161258-148077dd.pth
- Config: configs/psanet/psanet_r101-d8_512x512_160k_ade20k.py
  In Collection: psanet
  Metadata:
    backbone: R-101-D8
    crop size: (512,512)
    lr schd: 160000
  Name: psanet_r101-d8_512x512_160k_ade20k
  Results:
    Dataset: ADE20K
    Metrics:
      mIoU: 43.74
      mIoU(ms+flip): 45.38
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/psanet/psanet_r101-d8_512x512_160k_ade20k/psanet_r101-d8_512x512_160k_ade20k_20200615_161537-dbfa564c.pth
- Config: configs/psanet/psanet_r50-d8_512x512_20k_voc12aug.py
  In Collection: psanet
  Metadata:
    backbone: R-50-D8
    crop size: (512,512)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,512)
      value: 54.82
    lr schd: 20000
    memory (GB): 6.9
  Name: psanet_r50-d8_512x512_20k_voc12aug
  Results:
    Dataset: Pascal VOC 2012 + Aug
    Metrics:
      mIoU: 76.39
      mIoU(ms+flip): 77.34
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/psanet/psanet_r50-d8_512x512_20k_voc12aug/psanet_r50-d8_512x512_20k_voc12aug_20200617_102413-2f1bbaa1.pth
- Config: configs/psanet/psanet_r101-d8_512x512_20k_voc12aug.py
  In Collection: psanet
  Metadata:
    backbone: R-101-D8
    crop size: (512,512)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,512)
      value: 79.18
    lr schd: 20000
    memory (GB): 10.4
  Name: psanet_r101-d8_512x512_20k_voc12aug
  Results:
    Dataset: Pascal VOC 2012 + Aug
    Metrics:
      mIoU: 77.91
      mIoU(ms+flip): 79.3
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/psanet/psanet_r101-d8_512x512_20k_voc12aug/psanet_r101-d8_512x512_20k_voc12aug_20200617_110624-946fef11.pth
- Config: configs/psanet/psanet_r50-d8_512x512_40k_voc12aug.py
  In Collection: psanet
  Metadata:
    backbone: R-50-D8
    crop size: (512,512)
    lr schd: 40000
  Name: psanet_r50-d8_512x512_40k_voc12aug
  Results:
    Dataset: Pascal VOC 2012 + Aug
    Metrics:
      mIoU: 76.3
      mIoU(ms+flip): 77.35
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/psanet/psanet_r50-d8_512x512_40k_voc12aug/psanet_r50-d8_512x512_40k_voc12aug_20200613_161946-f596afb5.pth
- Config: configs/psanet/psanet_r101-d8_512x512_40k_voc12aug.py
  In Collection: psanet
  Metadata:
    backbone: R-101-D8
    crop size: (512,512)
    lr schd: 40000
  Name: psanet_r101-d8_512x512_40k_voc12aug
  Results:
    Dataset: Pascal VOC 2012 + Aug
    Metrics:
      mIoU: 77.73
      mIoU(ms+flip): 79.05
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/psanet/psanet_r101-d8_512x512_40k_voc12aug/psanet_r101-d8_512x512_40k_voc12aug_20200613_161946-1f560f9e.pth
