Collections:
- Metadata:
    Training Data:
    - Cityscapes
  Name: mobilenet_v3
Models:
- Config: configs/mobilenet_v3/lraspp_m-v3-d8_512x1024_320k_cityscapes.py
  In Collection: mobilenet_v3
  Metadata:
    backbone: M-V3-D8
    crop size: (512,1024)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,1024)
      value: 65.7
    lr schd: 320000
    memory (GB): 8.9
  Name: lraspp_m-v3-d8_512x1024_320k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 69.54
      mIoU(ms+flip): 70.89
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/mobilenet_v3/lraspp_m-v3-d8_512x1024_320k_cityscapes/lraspp_m-v3-d8_512x1024_320k_cityscapes_20201224_220337-cfe8fb07.pth
- Config: configs/mobilenet_v3/lraspp_m-v3-d8_scratch_512x1024_320k_cityscapes.py
  In Collection: mobilenet_v3
  Metadata:
    backbone: M-V3-D8 (scratch)
    crop size: (512,1024)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,1024)
      value: 67.7
    lr schd: 320000
    memory (GB): 8.9
  Name: lraspp_m-v3-d8_scratch_512x1024_320k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 67.87
      mIoU(ms+flip): 69.78
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/mobilenet_v3/lraspp_m-v3-d8_scratch_512x1024_320k_cityscapes/lraspp_m-v3-d8_scratch_512x1024_320k_cityscapes_20201224_220337-9f29cd72.pth
- Config: configs/mobilenet_v3/lraspp_m-v3s-d8_512x1024_320k_cityscapes.py
  In Collection: mobilenet_v3
  Metadata:
    backbone: M-V3s-D8
    crop size: (512,1024)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,1024)
      value: 42.3
    lr schd: 320000
    memory (GB): 5.3
  Name: lraspp_m-v3s-d8_512x1024_320k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 64.11
      mIoU(ms+flip): 66.42
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/mobilenet_v3/lraspp_m-v3s-d8_512x1024_320k_cityscapes/lraspp_m-v3s-d8_512x1024_320k_cityscapes_20201224_223935-61565b34.pth
- Config: configs/mobilenet_v3/lraspp_m-v3s-d8_scratch_512x1024_320k_cityscapes.py
  In Collection: mobilenet_v3
  Metadata:
    backbone: M-V3s-D8 (scratch)
    crop size: (512,1024)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,1024)
      value: 40.82
    lr schd: 320000
    memory (GB): 5.3
  Name: lraspp_m-v3s-d8_scratch_512x1024_320k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 62.74
      mIoU(ms+flip): 65.01
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/mobilenet_v3/lraspp_m-v3s-d8_scratch_512x1024_320k_cityscapes/lraspp_m-v3s-d8_scratch_512x1024_320k_cityscapes_20201224_223935-03daeabb.pth
