Collections:
- Metadata:
    Training Data:
    - ADE20K
  Name: swin
Models:
- Config: configs/swin/upernet_swin_tiny_patch4_window7_512x512_160k_ade20k_pretrain_224x224_1K.py
  In Collection: swin
  Metadata:
    backbone: Swin-T
    crop size: (512,512)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,512)
      value: 47.48
    lr schd: 160000
    memory (GB): 5.02
  Name: upernet_swin_tiny_patch4_window7_512x512_160k_ade20k_pretrain_224x224_1K
  Results:
    Dataset: ADE20K
    Metrics:
      mIoU: 44.41
      mIoU(ms+flip): 45.79
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/swin/upernet_swin_tiny_patch4_window7_512x512_160k_ade20k_pretrain_224x224_1K/upernet_swin_tiny_patch4_window7_512x512_160k_ade20k_pretrain_224x224_1K_20210531_112542-e380ad3e.pth
- Config: configs/swin/upernet_swin_small_patch4_window7_512x512_160k_ade20k_pretrain_224x224_1K.py
  In Collection: swin
  Metadata:
    backbone: Swin-S
    crop size: (512,512)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,512)
      value: 67.93
    lr schd: 160000
    memory (GB): 6.17
  Name: upernet_swin_small_patch4_window7_512x512_160k_ade20k_pretrain_224x224_1K
  Results:
    Dataset: ADE20K
    Metrics:
      mIoU: 47.72
      mIoU(ms+flip): 49.24
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/swin/upernet_swin_small_patch4_window7_512x512_160k_ade20k_pretrain_224x224_1K/upernet_swin_small_patch4_window7_512x512_160k_ade20k_pretrain_224x224_1K_20210526_192015-ee2fff1c.pth
- Config: configs/swin/upernet_swin_base_patch4_window7_512x512_160k_ade20k_pretrain_224x224_1K.py
  In Collection: swin
  Metadata:
    backbone: Swin-B
    crop size: (512,512)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,512)
      value: 79.05
    lr schd: 160000
    memory (GB): 7.61
  Name: upernet_swin_base_patch4_window7_512x512_160k_ade20k_pretrain_224x224_1K
  Results:
    Dataset: ADE20K
    Metrics:
      mIoU: 47.99
      mIoU(ms+flip): 49.57
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/swin/upernet_swin_base_patch4_window7_512x512_160k_ade20k_pretrain_224x224_1K/upernet_swin_base_patch4_window7_512x512_160k_ade20k_pretrain_224x224_1K_20210526_192340-593b0e13.pth
- Config: configs/swin/upernet_swin_base_patch4_window7_512x512_160k_ade20k_pretrain_224x224_22K.py
  In Collection: swin
  Metadata:
    backbone: Swin-B
    crop size: (512,512)
    lr schd: 160000
  Name: upernet_swin_base_patch4_window7_512x512_160k_ade20k_pretrain_224x224_22K
  Results:
    Dataset: ADE20K
    Metrics:
      mIoU: 50.31
      mIoU(ms+flip): 51.9
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/swin/upernet_swin_base_patch4_window7_512x512_160k_ade20k_pretrain_224x224_22K/upernet_swin_base_patch4_window7_512x512_160k_ade20k_pretrain_224x224_22K_20210526_211650-762e2178.pth
- Config: configs/swin/upernet_swin_base_patch4_window12_512x512_160k_ade20k_pretrain_384x384_1K.py
  In Collection: swin
  Metadata:
    backbone: Swin-B
    crop size: (512,512)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,512)
      value: 82.64
    lr schd: 160000
    memory (GB): 8.52
  Name: upernet_swin_base_patch4_window12_512x512_160k_ade20k_pretrain_384x384_1K
  Results:
    Dataset: ADE20K
    Metrics:
      mIoU: 48.35
      mIoU(ms+flip): 49.65
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/swin/upernet_swin_base_patch4_window12_512x512_160k_ade20k_pretrain_384x384_1K/upernet_swin_base_patch4_window12_512x512_160k_ade20k_pretrain_384x384_1K_20210531_132020-05b22ea4.pth
- Config: configs/swin/upernet_swin_base_patch4_window12_512x512_160k_ade20k_pretrain_384x384_22K.py
  In Collection: swin
  Metadata:
    backbone: Swin-B
    crop size: (512,512)
    lr schd: 160000
  Name: upernet_swin_base_patch4_window12_512x512_160k_ade20k_pretrain_384x384_22K
  Results:
    Dataset: ADE20K
    Metrics:
      mIoU: 50.76
      mIoU(ms+flip): 52.4
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/swin/upernet_swin_base_patch4_window12_512x512_160k_ade20k_pretrain_384x384_22K/upernet_swin_base_patch4_window12_512x512_160k_ade20k_pretrain_384x384_22K_20210531_125459-429057bf.pth
