Collections:
- Metadata:
    Training Data:
    - Cityscapes
    - ADE20k
  Name: mobilenet_v2
Models:
- Config: configs/mobilenet_v2/fcn_m-v2-d8_512x1024_80k_cityscapes.py
  In Collection: mobilenet_v2
  Metadata:
    backbone: M-V2-D8
    crop size: (512,1024)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,1024)
      value: 70.42
    lr schd: 80000
    memory (GB): 3.4
  Name: fcn_m-v2-d8_512x1024_80k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 61.54
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/mobilenet_v2/fcn_m-v2-d8_512x1024_80k_cityscapes/fcn_m-v2-d8_512x1024_80k_cityscapes_20200825_124817-d24c28c1.pth
- Config: configs/mobilenet_v2/pspnet_m-v2-d8_512x1024_80k_cityscapes.py
  In Collection: mobilenet_v2
  Metadata:
    backbone: M-V2-D8
    crop size: (512,1024)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,1024)
      value: 89.29
    lr schd: 80000
    memory (GB): 3.6
  Name: pspnet_m-v2-d8_512x1024_80k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 70.23
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/mobilenet_v2/pspnet_m-v2-d8_512x1024_80k_cityscapes/pspnet_m-v2-d8_512x1024_80k_cityscapes_20200825_124817-19e81d51.pth
- Config: configs/mobilenet_v2/deeplabv3_m-v2-d8_512x1024_80k_cityscapes.py
  In Collection: mobilenet_v2
  Metadata:
    backbone: M-V2-D8
    crop size: (512,1024)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,1024)
      value: 119.05
    lr schd: 80000
    memory (GB): 3.9
  Name: deeplabv3_m-v2-d8_512x1024_80k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 73.84
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/mobilenet_v2/deeplabv3_m-v2-d8_512x1024_80k_cityscapes/deeplabv3_m-v2-d8_512x1024_80k_cityscapes_20200825_124836-bef03590.pth
- Config: configs/mobilenet_v2/deeplabv3plus_m-v2-d8_512x1024_80k_cityscapes.py
  In Collection: mobilenet_v2
  Metadata:
    backbone: M-V2-D8
    crop size: (512,1024)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,1024)
      value: 119.05
    lr schd: 80000
    memory (GB): 5.1
  Name: deeplabv3plus_m-v2-d8_512x1024_80k_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 75.2
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/mobilenet_v2/deeplabv3plus_m-v2-d8_512x1024_80k_cityscapes/deeplabv3plus_m-v2-d8_512x1024_80k_cityscapes_20200825_124836-d256dd4b.pth
- Config: configs/mobilenet_v2/fcn_m-v2-d8_512x512_160k_ade20k.py
  In Collection: mobilenet_v2
  Metadata:
    backbone: M-V2-D8
    crop size: (512,512)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,512)
      value: 15.53
    lr schd: 160000
    memory (GB): 6.5
  Name: fcn_m-v2-d8_512x512_160k_ade20k
  Results:
    Dataset: ADE20k
    Metrics:
      mIoU: 19.71
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/mobilenet_v2/fcn_m-v2-d8_512x512_160k_ade20k/fcn_m-v2-d8_512x512_160k_ade20k_20200825_214953-c40e1095.pth
- Config: configs/mobilenet_v2/pspnet_m-v2-d8_512x512_160k_ade20k.py
  In Collection: mobilenet_v2
  Metadata:
    backbone: M-V2-D8
    crop size: (512,512)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,512)
      value: 17.33
    lr schd: 160000
    memory (GB): 6.5
  Name: pspnet_m-v2-d8_512x512_160k_ade20k
  Results:
    Dataset: ADE20k
    Metrics:
      mIoU: 29.68
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/mobilenet_v2/pspnet_m-v2-d8_512x512_160k_ade20k/pspnet_m-v2-d8_512x512_160k_ade20k_20200825_214953-f5942f7a.pth
- Config: configs/mobilenet_v2/deeplabv3_m-v2-d8_512x512_160k_ade20k.py
  In Collection: mobilenet_v2
  Metadata:
    backbone: M-V2-D8
    crop size: (512,512)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,512)
      value: 25.06
    lr schd: 160000
    memory (GB): 6.8
  Name: deeplabv3_m-v2-d8_512x512_160k_ade20k
  Results:
    Dataset: ADE20k
    Metrics:
      mIoU: 34.08
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/mobilenet_v2/deeplabv3_m-v2-d8_512x512_160k_ade20k/deeplabv3_m-v2-d8_512x512_160k_ade20k_20200825_223255-63986343.pth
- Config: configs/mobilenet_v2/deeplabv3plus_m-v2-d8_512x512_160k_ade20k.py
  In Collection: mobilenet_v2
  Metadata:
    backbone: M-V2-D8
    crop size: (512,512)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,512)
      value: 23.2
    lr schd: 160000
    memory (GB): 8.2
  Name: deeplabv3plus_m-v2-d8_512x512_160k_ade20k
  Results:
    Dataset: ADE20k
    Metrics:
      mIoU: 34.02
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/mobilenet_v2/deeplabv3plus_m-v2-d8_512x512_160k_ade20k/deeplabv3plus_m-v2-d8_512x512_160k_ade20k_20200825_223255-465a01d4.pth
