Collections:
- Metadata:
    Training Data:
    - Cityscapes
  Name: fp16
Models:
- Config: configs/fp16/fcn_r101-d8_512x1024_80k_fp16_cityscapes.py
  In Collection: fp16
  Metadata:
    backbone: R-101-D8
    crop size: (512,1024)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,1024)
      value: 115.74
    lr schd: 80000
    memory (GB): 5.37
  Name: fcn_r101-d8_512x1024_80k_fp16_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 76.8
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fp16/fcn_r101-d8_512x1024_80k_fp16_cityscapes/fcn_r101-d8_512x1024_80k_fp16_cityscapes-50245227.pth
- Config: configs/fp16/pspnet_r101-d8_512x1024_80k_fp16_cityscapes.py
  In Collection: fp16
  Metadata:
    backbone: R-101-D8
    crop size: (512,1024)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,1024)
      value: 114.03
    lr schd: 80000
    memory (GB): 5.34
  Name: pspnet_r101-d8_512x1024_80k_fp16_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 79.46
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fp16/pspnet_r101-d8_512x1024_80k_fp16_cityscapes/pspnet_r101-d8_512x1024_80k_fp16_cityscapes-ade37931.pth
- Config: configs/fp16/deeplabv3_r101-d8_512x1024_80k_fp16_cityscapes.py
  In Collection: fp16
  Metadata:
    backbone: R-101-D8
    crop size: (512,1024)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,1024)
      value: 259.07
    lr schd: 80000
    memory (GB): 5.75
  Name: deeplabv3_r101-d8_512x1024_80k_fp16_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 80.48
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fp16/deeplabv3_r101-d8_512x1024_80k_fp16_cityscapes/deeplabv3_r101-d8_512x1024_80k_fp16_cityscapes-bc86dc84.pth
- Config: configs/fp16/deeplabv3plus_r101-d8_512x1024_80k_fp16_cityscapes.py
  In Collection: fp16
  Metadata:
    backbone: R-101-D8
    crop size: (512,1024)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,1024)
      value: 127.06
    lr schd: 80000
    memory (GB): 6.35
  Name: deeplabv3plus_r101-d8_512x1024_80k_fp16_cityscapes
  Results:
    Dataset: Cityscapes
    Metrics:
      mIoU: 80.46
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/fp16/deeplabv3plus_r101-d8_512x1024_80k_fp16_cityscapes/deeplabv3plus_r101-d8_512x1024_80k_fp16_cityscapes-cc58bc8d.pth
