Collections:
- Metadata:
    Training Data:
    - ADE20k
  Name: segformer
Models:
- Config: configs/segformer/segformer_mit-b0_512x512_160k_ade20k.py
  In Collection: segformer
  Metadata:
    backbone: MIT-B0
    crop size: (512,512)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,512)
      value: 19.49
    lr schd: 160000
    memory (GB): 2.1
  Name: segformer_mit-b0_512x512_160k_ade20k
  Results:
    Dataset: ADE20k
    Metrics:
      mIoU: 37.41
      mIoU(ms+flip): 38.34
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/segformer/segformer_mit-b0_512x512_160k_ade20k/segformer_mit-b0_512x512_160k_ade20k_20210726_101530-8ffa8fda.pth
- Config: configs/segformer/segformer_mit-b1_512x512_160k_ade20k.py
  In Collection: segformer
  Metadata:
    backbone: MIT-B1
    crop size: (512,512)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,512)
      value: 20.98
    lr schd: 160000
    memory (GB): 2.6
  Name: segformer_mit-b1_512x512_160k_ade20k
  Results:
    Dataset: ADE20k
    Metrics:
      mIoU: 40.97
      mIoU(ms+flip): 42.54
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/segformer/segformer_mit-b1_512x512_160k_ade20k/segformer_mit-b1_512x512_160k_ade20k_20210726_112106-d70e859d.pth
- Config: configs/segformer/segformer_mit-b2_512x512_160k_ade20k.py
  In Collection: segformer
  Metadata:
    backbone: MIT-B2
    crop size: (512,512)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,512)
      value: 32.38
    lr schd: 160000
    memory (GB): 3.6
  Name: segformer_mit-b2_512x512_160k_ade20k
  Results:
    Dataset: ADE20k
    Metrics:
      mIoU: 45.58
      mIoU(ms+flip): 47.03
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/segformer/segformer_mit-b2_512x512_160k_ade20k/segformer_mit-b2_512x512_160k_ade20k_20210726_112103-cbd414ac.pth
- Config: configs/segformer/segformer_mit-b3_512x512_160k_ade20k.py
  In Collection: segformer
  Metadata:
    backbone: MIT-B3
    crop size: (512,512)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,512)
      value: 45.23
    lr schd: 160000
    memory (GB): 4.8
  Name: segformer_mit-b3_512x512_160k_ade20k
  Results:
    Dataset: ADE20k
    Metrics:
      mIoU: 47.82
      mIoU(ms+flip): 48.81
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/segformer/segformer_mit-b3_512x512_160k_ade20k/segformer_mit-b3_512x512_160k_ade20k_20210726_081410-962b98d2.pth
- Config: configs/segformer/segformer_mit-b4_512x512_160k_ade20k.py
  In Collection: segformer
  Metadata:
    backbone: MIT-B4
    crop size: (512,512)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,512)
      value: 64.72
    lr schd: 160000
    memory (GB): 6.1
  Name: segformer_mit-b4_512x512_160k_ade20k
  Results:
    Dataset: ADE20k
    Metrics:
      mIoU: 48.46
      mIoU(ms+flip): 49.76
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/segformer/segformer_mit-b4_512x512_160k_ade20k/segformer_mit-b4_512x512_160k_ade20k_20210728_183055-7f509d7d.pth
- Config: configs/segformer/segformer_mit-b5_512x512_160k_ade20k.py
  In Collection: segformer
  Metadata:
    backbone: MIT-B5
    crop size: (512,512)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,512)
      value: 84.1
    lr schd: 160000
    memory (GB): 7.2
  Name: segformer_mit-b5_512x512_160k_ade20k
  Results:
    Dataset: ADE20k
    Metrics:
      mIoU: 49.13
      mIoU(ms+flip): 50.22
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/segformer/segformer_mit-b5_512x512_160k_ade20k/segformer_mit-b5_512x512_160k_ade20k_20210726_145235-94cedf59.pth
- Config: configs/segformer/segformer_mit-b5_640x640_160k_ade20k.py
  In Collection: segformer
  Metadata:
    backbone: MIT-B5
    crop size: (640,640)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (640,640)
      value: 88.5
    lr schd: 160000
    memory (GB): 11.5
  Name: segformer_mit-b5_640x640_160k_ade20k
  Results:
    Dataset: ADE20k
    Metrics:
      mIoU: 49.62
      mIoU(ms+flip): 50.36
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/segformer/segformer_mit-b5_640x640_160k_ade20k/segformer_mit-b5_640x640_160k_ade20k_20210801_121243-41d2845b.pth
