Collections:
- Metadata:
    Training Data:
    - ADE20K
  Name: setr
Models:
- Config: configs/setr/setr_naive_512x512_160k_b16_ade20k.py
  In Collection: setr
  Metadata:
    backbone: ViT-L
    crop size: (512,512)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,512)
      value: 211.86
    lr schd: 160000
    memory (GB): 18.4
  Name: setr_naive_512x512_160k_b16_ade20k
  Results:
    Dataset: ADE20K
    Metrics:
      mIoU: 48.28
      mIoU(ms+flip): 49.56
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/setr/setr_naive_512x512_160k_b16_ade20k/setr_naive_512x512_160k_b16_ade20k_20210619_191258-061f24f5.pth
- Config: configs/setr/setr_pup_512x512_160k_b16_ade20k.py
  In Collection: setr
  Metadata:
    backbone: ViT-L
    crop size: (512,512)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,512)
      value: 222.22
    lr schd: 160000
    memory (GB): 19.54
  Name: setr_pup_512x512_160k_b16_ade20k
  Results:
    Dataset: ADE20K
    Metrics:
      mIoU: 48.24
      mIoU(ms+flip): 49.99
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/setr/setr_pup_512x512_160k_b16_ade20k/setr_pup_512x512_160k_b16_ade20k_20210619_191343-7e0ce826.pth
- Config: configs/setr/setr_mla_512x512_160k_b8_ade20k.py
  In Collection: setr
  Metadata:
    backbone: ViT-L
    crop size: (512,512)
    lr schd: 160000
    memory (GB): 10.96
  Name: setr_mla_512x512_160k_b8_ade20k
  Results:
    Dataset: ADE20K
    Metrics:
      mIoU: 47.34
      mIoU(ms+flip): 49.05
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/setr/setr_mla_512x512_160k_b8_ade20k/setr_mla_512x512_160k_b8_ade20k_20210619_191118-c6d21df0.pth
- Config: configs/setr/setr_mla_512x512_160k_b16_ade20k.py
  In Collection: setr
  Metadata:
    backbone: ViT-L
    crop size: (512,512)
    inference time (ms/im):
    - backend: PyTorch
      batch size: 1
      hardware: V100
      mode: FP32
      resolution: (512,512)
      value: 190.48
    lr schd: 160000
    memory (GB): 17.3
  Name: setr_mla_512x512_160k_b16_ade20k
  Results:
    Dataset: ADE20K
    Metrics:
      mIoU: 47.54
      mIoU(ms+flip): 49.37
    Task: Semantic Segmentation
  Weights: https://download.openmmlab.com/mmsegmentation/v0.5/setr/setr_mla_512x512_160k_b16_ade20k/setr_mla_512x512_160k_b16_ade20k_20210619_191057-f9741de7.pth
